### PR TITLE
Added Head request

### PR DESCRIPTION
**Pull request by rodrigopavezi**
@tejohnso @fjvallarino what do you think about this changes? does that make sense? cheers

### CODE REVIEW

**Comment by tejohnso** [comment]
@rodrigopavezi Why do you duplicate certain variables?  Like on line 5.

**Comment by tejohnso** [comment]
Actually @rodrigopavezi I sent you a meeting request for 11am, let's talk there.

**Comment by rodrigopavezi** [comment]
@tejohnso I made the changes and test it with the Jay Peak presentation. It is working now :-). It was not working with a Jay Peak presentation that was using a test version of the storage component. I have changed also the storage component to have only HEAD request and it still working with this version of CAP. All look good. please review. cheers

**Comment by tejohnso** [comment]
@rodrigopavezi Great!  :+1:

**Pull request merged**
