### PR TITLE
RiseCache webkitRequestFileSystem changes

### PR DESCRIPTION
**Pull request by mfarooq2000**
@tejohnso please review. Thanks

### CODE REVIEW

**Comment by mfarooq2000** [comment]
@tejohnso fixed issues #37, #40 and #41

**Comment by tejohnso** [comment]
Can you explain the overall goal with these changes?
Why are we using webkitrequestfilesystem instead of chrome.filesystem?

**Comment by mfarooq2000** [comment]
@tejohnso we were using webkitrequestfilesystemSync and that started crashing on CROS, so changed that to webkitrequestfilesystem. 

As I am reading chrome.filesystem is based on webkitrequestfilesystem, we can consider that in future.

**Comment by tejohnso** [comment]
:+1:

**Comment by mfarooq2000** [comment]
@tejohnso Thanks

**Pull request merged**
